name: Build toolset

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build-toolset:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependenciess
      run: dotnet restore
    - name: Build
      run: dotnet build -c release --no-restore
    - name: Publish
      run: dotnet publish -c release --no-restore --no-build
    - name: Organize files
      run: |
        mkdir Deployment
        mv .\WinthainerCommand\bin\Release\net5.0\win-x64\publish\ .\Deployment\WinthainerCommand
        mv .\WinthainerService\bin\Release\net5.0-windows\win-x64\publish\ .\Deployment\WinthainerService
        mv .\WinthainerInstaller\bin\Release\net5.0\win-x64\publish\WinthainerInstaller.exe .\Deployment\
    - name: Zip deployment
      run : Compress-Archive -Path .\Deployment\* -DestinationPath .\WinthainerToolset.zip
    - name: Upload deployment
      uses: actions/upload-artifact@v2
      with:
        name: WinthainerToolset.zip
        path: ./WinthainerToolset.zip
        retention-days: 1