name: Build distribution

on:
  push:
    branches: [ feature/distribution-build ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install requirements
      run: sudo apt install libarchive-tools
    - name: Download Alpine minirootfs
      run: wget https://dl-cdn.alpinelinux.org/alpine/v3.14/releases/x86_64/alpine-minirootfs-3.14.2-x86_64.tar.gz
    - name: Unpack Alpine minirootfs
      run: |
        mkdir minirootfs
        bsdtar -xpf alpine-minirootfs-3.14.2-x86_64.tar.gz -C minirootfs
    - name: Chroot Alpine minirootfs
      run: |
        sudo chroot ./minirootfs /bin/ash -c apk update