name: Build distributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
      
jobs:
  build-engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: sudo apt install libarchive-tools
      - name: Download Debian rootfs
        run: wget https://salsa.debian.org/debian/WSL/-/raw/master/x64/install.tar.gz
      - name: Unpack Debian rootfs
        run: |
          mkdir rootfs
          echo `bsdtar -xpf install.tar.gz -C rootfs`
      - name: Chroot Debian rootfs
        run: |
          sudo cp /etc/resolv.conf ./rootfs/etc/resolv.conf
          sudo chroot ./rootfs /bin/bash -c "apt update"
          sudo chroot ./rootfs /bin/bash -c "apt -y install ca-certificates curl gnupg lsb-release"
          sudo chroot ./rootfs /bin/bash -c "mkdir -p /etc/apt/keyrings"
          sudo chroot ./rootfs /bin/bash -c "curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
          sudo chroot ./rootfs /bin/bash -c "echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list"
          sudo chroot ./rootfs /bin/bash -c "apt update"
          sudo chroot ./rootfs /bin/bash -c "apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin"
          sudo cp Resources/daemon.json ./rootfs/etc/docker/
          sudo rm ./rootfs/etc/resolv.conf
      - name: Create tarball from rootfs
        run: |
          cd ./rootfs
          bsdtar -a -cf ../WinthainerEngine.tar.gz *
      - name: Upload distribution
        uses: actions/upload-artifact@v2
        with:
          name: WinthainerEngine.tar.gz
          path: ./WinthainerEngine.tar.gz
          retention-days: 7
  build-data:
    runs-on: ubuntu-latest
    steps:
      - name: Download Alpine minirootfs
        run: wget https://dl-cdn.alpinelinux.org/alpine/v3.15/releases/x86_64/alpine-minirootfs-3.15.4-x86_64.tar.gz
      - name: Upload distribution
        uses: actions/upload-artifact@v2
        with:
          name: WinthainerData.tar.gz
          path: ./alpine-minirootfs-3.15.4-x86_64.tar.gz
          retention-days: 7