name: Build distribution

on:
  push:
    branches: [ feature/distribution-build ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install requirements
      run: sudo apt install bsdtar
    - name: Download Alpine minirootfs
      run: wget https://dl-cdn.alpinelinux.org/alpine/v3.14/releases/x86_64/alpine-minirootfs-3.14.2-x86_64.tar.gz
    - name: Unpack Alpine minirootfs
      run: bsdtar -xpf ArchLinuxARM-rpi-4-latest.tar.gz -C minirottfs
    - name: Chroot Alpine minirootfs
      run: |
        chroot ./minirottfs
        apk update