name: Release toolset

on:
  push:
    tags:
      - "v*"

jobs:
  build-toolset:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependenciess
        run: dotnet restore
      - name: Build
        run: dotnet build -c release --no-restore
      - name: Publish
        run: dotnet publish -c release --no-restore --no-build
      - name: Organize files
        run: |
          mkdir Deployment
          mv .\WinthainerCommand\bin\Release\net5.0\win-x64\publish\ .\Deployment\WinthainerCommand
          mv .\WinthainerService\bin\Release\net5.0-windows\win-x64\publish\ .\Deployment\WinthainerService
          mv .\WinthainerInstaller\bin\Release\net5.0\win-x64\publish\WinthainerInstaller.exe .\Deployment\
      - name: Zip deployment
        run : Compress-Archive -Path .\Deployment\* -DestinationPath .\WinthainerToolsetRelease.zip
      - name: Upload deployment
        uses: actions/upload-artifact@v2
        with:
          name: WinthainerToolsetRelease.zip
          path: ./WinthainerToolsetRelease.zip
          retention-days: 1
  release-toolset:
    runs-on: windows-latest
    needs: [build-toolset]
    steps:
      - name: Load toolset
        uses: actions/download-artifact@v2
        with:
          name: WinthainerToolsetRelease.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            WinthainerToolsetRelease.zip